# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Python from virtual environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  
      - name: Install dependencies
        run: |
          source fastapi/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Run Flake8
        run: |
          flake8 --max-line-length 99
      - name: Run pytest
        run: pytest
